apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-deploy
  labels:
    app: banking
spec:
  replicas: 3
  selector:
    matchLabels:
      app: banking
  template:
    metadata:
      labels:
        app: banking
    spec:
      containers:
      - name: banking-container
        image: abhilashdr123/banking 
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: banking-service
  labels:
    app: banking
spec:
  selector:
    app: banking

  type: NodePort
  ports:
  - nodePort: 31032    
    port: 8082
    targetPort: 8082
